# Keyboard firmware features
CAPS_WORD_ENABLE = yes
FORCE_NKRO = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
LEADER_ENABLE = yes
UNICODE_COMMON = yes
